spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sonet'
    username: 'compose-postgres'
    password: 'compose-postgres'
  hikari:
    auto-commit: true
    leak-detection-threshold: 60000
    allow-pool-suspension: true
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 60000
  jackson:
    date-format: 'yyyy-MM-dd'
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml